title: Rahul Ranjan  
logo: "/Screenshot 2024-05-14 123629.png"
description: Showcase of my skills, work and leadership experience, and M.S. and B.S. projects. 
show_downloads: true
theme: jekyll-theme-minimal
